### ISSUE TITLE
Akegreya Devnagri font (see image) 

### ISSUE THREAD

**Issue by mohitWrangler** [huertatipografica/sahitya#1]
![screenshot_2015-05-28-20-54-16](https://cloud.githubusercontent.com/assets/5771169/7864315/e55d0980-057e-11e5-9da3-7251dbebec9e.jpg)

![Uploading Screenshot_2015-05-28-20-54

i came to this github link searching for Alegreya Devnagari font , its only English font in this github

Where can I get Akegreya Devnagri font (see image) ?

**Comment by juandelperal** [comment]
Hi @mohitWrangler, this is the repo of Alegreya Devanagari. You can download the files (latin + devnagari) here: https://github.com/juandelperal/sahitya/tree/master/otf
Cheers!
