### ISSUE TITLE
Fix shaping for Safari

### ISSUE THREAD

**Issue by davelab6** [huertatipografica/sahitya#2]
When I use Safari Version 7.1.6 on Mac OS X 10.9 to review http://www.impallari.com/testing/index-devanagari.php#sample_one (you need to click the 'Sample 1' tab link near the top right) then the shaping isn't working :(

**Comment by juandelperal** [comment]
Now is fixed. Thanks @davelab6

**Comment by davelab6** [comment]
Awesome!

**Comment by davelab6** [comment]
Nice!
